### ISSUE TITLE
Update environment managers FAQ with actual MPIA guidance

### ISSUE THREAD

**Issue by ivastar** [mpi-astronomy/FAQ#20]
Yes, conda itself is open source and we can still use it (https://stackoverflow.com/questions/74762863/are-conda-miniconda-and-anaconda-free-to-use-and-open-source)

-----------------

Hi Iva,

Thanks for this. I know about the Anaconda problem, and I changed my system to use conda through https://conda-forge.org/ instead of anaconda, as per IT's recommendations. Your environment page mentioned below, however, sort of implies *any* use of conda is contrary to MPG regulations, but I believe that is not the case. It might be good to clarify this in the document, and point out that use of conda via conda-forge is okay, even if you no longer recommend conda per se.

Regards,

Coryn.

**Comment by TheSkyentist** [comment]
#19 Adds miniforge to the FAQ, so perhaps it will help give folks the clarity they need?

**Comment by mfouesneau** [comment]
Thanks  closed with #[1251936](https://github.com/mpi-astronomy/FAQ/commit/12519367e1f818d3c83944090387f98a423e9edb)
