### ISSUE TITLE
README.md out of date. 

### ISSUE THREAD

**Issue by TheSkyentist** [mpi-astronomy/FAQ#3]
Main [README.md](https://github.com/mpi-astronomy/FAQ/blob/c22327904aa78e471c6cdb7b1b1d5dc1e4c7e6b2/README.md) for repository is out of date and most of the links are broken. Either updating the links or removing the current text in the README.md and directing to the live site are solutions.

**Comment by mfouesneau** [comment]
Removed individual links.
